[project]
name = "voting-proxy"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.membership-registry]
path = "contracts/membership-registry.clar"
depends_on = []

[contracts.token-vote-power]
path = "contracts/token-vote-power.clar"
depends_on = []

[contracts.voting-proxy]
path = "contracts/voting-proxy.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
